### ISSUE TITLE
provide builtin variables related to the comment's context

### ISSUE THREAD

**Issue by jizhilong** [nwtgck/actions-comment-run#20]
This is a feature request.

First of all, this tool is really cool, I can't help to start using it in my daily job(well, actually I do most of my work on our company's self-hosted GitLab, so I wish there was a GitLab port of `actions-comment-run`, but that's another thread then). 

As a potential user of `actions-comment-run`, I think if there are some variables( representing the current issue/pr/project/user who invoke the bot,) available in the execution context,  it would benefits a lot.

**Comment by nwtgck** [comment]
@jizhilong Thanks for the feature request.

Do you mean comment-run should provide available variables in the comment script? Is my understanding correct? For example, currently, `githubToken`, `githubClient`, `postComment()`, `context`... are available. If you mean this, I also think the list of available variables should be documented.

**Comment by jizhilong** [comment]
> Do you mean comment-run should provide available variables in the comment script? Is my understanding correct

Yes, You are right.

> For example, currently, githubToken, githubClient, postComment(), context

After some digging in [the code](https://github.com/nwtgck/actions-comment-run/blob/develop/src/main.ts), I think `context` would be exactly what I want.

**Comment by nwtgck** [comment]
@jizhilong Thanks for your reply. I'll document to list all available variables which are guaranteed used in the js-comment context.

**Comment by nwtgck** [comment]
@jizhilong I made a list of available build-in variables.
see: https://github.com/nwtgck/actions-comment-run/tree/6bea6fb49b8a3e2253f5e2e9ebfded12caf17113#available-variables-in-the-js-comment-context

Please feel free to reopen or create new one when the list is not enough or you have feature request.

**Comment by jizhilong** [comment]
> so I wish there was a GitLab port of actions-comment-run, but that's another thread then

Hi @nwtgck , just want to let you know I made a GitLab port in our self-hosted gitlab server via [file hook](https://docs.gitlab.com/ee/administration/file_hooks.html)，and I find it really useful:

![image](https://user-images.githubusercontent.com/816618/81463346-961c4a80-91eb-11ea-9ff2-7534125b2aac.png)
