### ISSUE TITLE
examples that trigger githubClient seems to not work

### ISSUE THREAD

**Issue by bdougie** [nwtgck/actions-comment-run#22]
Hello, thanks for sharing this Action with the community. 

I am testing it out in my personal repo here: https://github.com/bdougie/bot-test-repo/issues/413

I can get the simple hello world to work, but when trying to use the examples with `githubClient` it does not print a comment. It only acknowledges the Action completed with a reaction.

Any chance you could help me understand how to debug this?

Aside: Even after [reading the code](https://github.com/nwtgck/actions-comment-run/blob/develop/src/main.ts#L94-L116), it is not clear why the 👀 is added as a reaction. I understand the  :+1: to be a signal the Action completed.

**Comment by nwtgck** [comment]
@bdougie Thanks. To run JavaScript, you have to use ```` ```js ````. I guess you use ```` ``` ````.

**Comment by bdougie** [comment]
Awesome, it works with the ```js.

**Comment by bdougie** [comment]
Any chance you could shed some light on the reactions and what they mean as well?

In particular the 👀 and 👍

**Comment by nwtgck** [comment]
@bdougie 

> Aside: Even after reading the code, it is not clear why the 👀 is added as a reaction. I understand the 👍 to be a signal the Action completed.

This is right. When it starts, the action reacts with :eyes:. After finished without failure (no matter 0 scripts runs), the action reacts with 👍 .

**Comment by bdougie** [comment]
Thanks for the help and the info. I can close this out. 

Turns out this was a copy and paste error.

**Comment by nwtgck** [comment]
@bdougie 
However, when I see your comments, reaction with 👍  when no script runs confuses the users. In the future, I may change the behavior.
