### ISSUE TITLE
await is only valid in async function

### ISSUE THREAD

**Issue by kaihendry** [nwtgck/actions-comment-run#51]
I'm trying a couple of examples upon:
https://github.com/kaihendry/dabase.com/pull/7

And I'm getting as you can see upon
https://github.com/kaihendry/dabase.com/actions/runs/68702196

```await is only valid in async function``` error.

I think it's because:

    mkdir -p .github/workflows/ && cd .github/workflows/ && wget https://gist.githubusercontent.com/nwtgck/a9b291f6869db42ecc3d9e30d0a0494c/raw/comment-run.yml

Which is v1 not v1.1

**Comment by nwtgck** [comment]
@kaihendry Thank you for reporting.

Have you solved the problem with v1 or v1.1? But anyway, I'll update the Gist code.

**Comment by kaihendry** [comment]
I updated to 1.1. Ideally I could just be running latest? How do I express that?

**Comment by nwtgck** [comment]
@kaihendry This one is an expected behavior.

<img width="773" alt="image" src="https://user-images.githubusercontent.com/10933561/78245644-cb65b680-7522-11ea-8e0f-4e7968725f25.png">

Actual comment: https://github.com/nwtgck/actions-comment-run/issues/30#issuecomment-607794822

**Comment by nwtgck** [comment]
@kaihendry Did you solve this problem?

**Comment by kaihendry** [comment]
Yes, though is there a way to fix on your latest workflow version? Does @latest work I wonder? :laughing:

**Comment by nwtgck** [comment]
@kaihendry When you use v1, v1.1 or v1.1.2, it's ok. I don't provide `@latest`.

**Comment by nwtgck** [comment]
Could you solve this problem? I'd like close this issue.
