### ISSUE TITLE
  Identifier 'githubClient' has already been declared

### ISSUE THREAD

**Issue by kaihendry** [nwtgck/actions-comment-run#52]
You need to remove githubClient from the https://github.com/nwtgck/actions-comment-run#pr-merge-preview example since it's not an available variable https://github.com/nwtgck/actions-comment-run#available-variables-in-the-js-comment-context

**Comment by nwtgck** [comment]
@kaihendry Thanks.

As you said `githubClient` is available variable, but they aren't conflicted.

**Comment by nwtgck** [comment]
@github-actions run

```js
const githubClient = new GitHub(githubToken);
await postComment(typeof githubClient);
```

**Comment by nwtgck** [comment]
@kaihendry You are right. The following code caused an error.

```js
const githubClient = new GitHub(githubToken);
await postComment(typeof githubClient);
```

error:
![image](https://user-images.githubusercontent.com/10933561/78359807-bc4d3a00-75f0-11ea-9dbc-6fe35147d8f2.png)
